variables:
    IMG_NAME: myassineboum/gitlab-ci-pipeline
    IMG_TAG: v1

stages:
    - install
    - build
    - deploy

install_dep:
    stage: install
    image: openjdk:17
    services:
        - maven:latest
    script:
        - mvn clean install -Dmaven.test.skip=true

build_img:
    stage: build
    image: docker:latest
    services:
        - docker:25.0.1-dind
    before_script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
    script:
        - docker build -t $IMG_NAME:$IMG_TAG .
        - docker push $IMG_NAME:$IMG_TAG
    