variables:
    IMG_NAME: myassineboum/gitlab-ci-pipeline
    IMG_TAG: v1

include:
  - template: Security/Container-Scanning.gitlab-ci.yml

stages:
    - install
    - build
    - scan

install_dep:
    stage: install
    image: maven:3-sapmachine-17
    script:
        - mvn clean install
        - mvn package

build_img:
    stage: build
    image: docker:latest
    services:
        - docker:25.0.1-dind
    before_script:
        - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
    script:
        - docker build -t $IMG_NAME:$IMG_TAG .
        - docker push $IMG_NAME:$IMG_TAG

container_scanning:
    stage: scan
    script:
        - echo "Scanning the image..."
    variables:
        CS_IMAGE: $IMG_NAME:$IMG_TAG