variables:
    IMG_NAME: myassineboum/gitlab-ci-pipeline
    IMG_TAG: v1
    MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"

stages:
    - install
    - build
    - deploy

install_dep:
    stage: install
    image: maven:latest
    script:
        - mvn $MAVEN_CLI_OPTS install

build_img:
    stage: build
    image: docker:latest
    services:
        - docker:25.0.1-dind
    before_script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
    script:
        - docker build -t $IMG_NAME:$IMG_TAG .
        - docker push $IMG_NAME:$IMG_TAG
    